version: '3'
services:
  spring-server:
    build:
      context: ./spring-server
    ports:
      - "8086:8086"
    env_file:
      - ./spring-server/.env
    container_name: spring-server
    restart: always
