version: "3.8"

services:
  spring-server:
    build: .
    container_name: spring-server
    ports:
      - "8086:8086"
    env_file:
      - .env        # ✅ .env 파일에서 모든 환경 변수 자동 불러오기
    restart: always
    networks:
      - neverland-network

networks:
  neverland-network:
    driver: bridge
