services:
  spring-server:
    build:
      context: ./spring-server
    ports:
      - "8086:8086"
    env_file:
      - .env
    container_name: spring-server
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s